language: cpp
sudo: false
dist: trusty
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "RN4+VU9GAbcLnlYQYuHtVx3Lf99vXCy4Bg2CTgaORmzVFZdtSySPVIkkp9DVqDNYt9JQS8xIlAGEzu7N4R+6dX24pnbUmqsX8DipxRTS8y6q0glB9XoVpSQmUGw0RWoHHnecIjrwUwsZUp2Ebgc0Q9mPx4YynX8sTTW2/fgNEZUslNqKFMN0HPBgTkPnt9KoLB6aynRAjKJWau11qQ00qcZUuN2LfDCp02EHeypQ6GAWnAfcnOlkUXufq0sl7onH2UBR4pnDC+E0DlrGXpDGADnwl6gQR4WZuxAab0Ulnx3plK7wOiY1Odh7P87nWiWZL0JqMLgKu4yAcoMVNlP9EAhYrnYxtOginAICoCh2JqEKdtpUoC5vHBtaV8TOFxd7IkKyq6Jn68x3BTugjNdLyE8ZJjhbg0R9gIsvUrx8CLfvXdxMnnGTZAmsX0P+a4+mUHUzJRhW/DEiAPDbXfcF7I8HejNscfPNIKDsGaDm/9iUd7lzsmc+PEss3e0CKfiIWlsKhin5bqRn18lVDaPEUKWCq5YF/JV7J93looHJQ2JgQVRAIk8b26TRZdc+UiTM/t/u+2XOwD9sYo2J+hzDCmWEuUQWiaM3XhOL++IIV01pbIeebD5/VjPiBo54PIMG25jZ+VncIxmkAPl1d39KN2bKUy2Lk6W/rRUToVhfSpw="
before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - test -n $FC && unset FC
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake3
      - g++-7
      - gcc-7
      - gfortran-7
      - libboost-math-dev
  coverity_scan:
    project:
      name: "PCMSolver/pcmsolver"
      description: "An API for the Polarizable Continuum Model"
    notification_email: roberto.diremigio@gmail.com
    build_command_prepend: "python setup.py --cxx=g++-7 --cc=gcc-7 --fc=gfortran-7 --type=debug --ccache=off --cmake-options='-DENABLE_TESTS=OFF -DENABLE_Fortran_API=ON'"
    build_command: "cmake --build build -- VERBOSE=1 -j 2"
    branch_pattern: coverity_scan
script:
  - cmake --build build -- VERBOSE=1 -j 2
